github:
  username: ${{ github.actor }}
  token:    ${{ secrets.SSLCNB_GITHUB_TOKEN }}

package:
  repository:     "ghcr.io/${{ github.actor }}/${{ github.repository }}"

docker_credentials:
  - registry: ghcr.io
    username: ${{ github.actor }}
    password: ${{ secrets.SSLCNB_GITHUB_TOKEN }}
